In [23]:
import torch

## 1. scatter_()

to scatter (or update) elements of a tensor with values from another tensor based on specified indices. 

- scatter() vs scatter_() ; _() are in-place operations, they change the tensor directly, while scatter() is out-of-operaiton, it returns a new tensor with the scattered values.

In [29]:
# a tensor to modify 

x = torch.zeros(2,5, dtype=torch.int64)
x

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]])

In [28]:
# define indices to scatter values

idx = torch.tensor([[0], [3]])
idx


tensor([[0],
        [3]])

In [43]:
# some values 
# exactly in the shape of x having some random values 

values = torch.randint(x.shape[0]*x.shape[1], (x.shape))
values

tensor([[7, 1, 9, 8, 0],
        [6, 3, 4, 5, 7]])

In [47]:
x.scatter_(1, idx, values)

tensor([[7, 0, 0, 0, 0],
        [0, 0, 0, 6, 0]])